name: Django Continuous Integration & Testing

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  code_scan:

    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v6.0.1
      with:
        repository: ${{ github.repository }}

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Bandit Code Scanner
      run: pip install bandit

    - name: Run Bandit Scan
      run: bandit --severity-level=medium --confidence-level=medium -r . -f json -o bandit-scan-report.json

    - name: Upload Bandit Artifact
      uses: actions/upload-artifact@v6.0.0
      if: always()
      with:
        name: bandit-scan-artifact
        path: bandit-scan-report.json

  image_scan:
    needs: code_scan

    name: Build Image and Run Image Scan
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v6.0.1
      with:
        repository: ${{ github.repository }}

    - name: Set up Docker
      uses: docker/setup-docker-action@v4.6.0
      with:
        version: 24.0.9

    - name: Build Docker Image
      run: docker build -f Dockerfile -t djangoapp:latest .

    - name: Scan using Docker Scout
      uses: docker/scout-action@v1.18.2
      with:
        dockerhub-user: ${{ secrets.DOCKER_USER }}
        dockerhub-password: ${{ secrets.DOCKER_PWD }}
        command: quickview,cves
        only-severities: critical,high
        sarif-file: docker-scout-report.sarif
        exit-code: true

    - name: Upload Docker Scout Artifact
      uses: actions/upload-artifact@v6.0.0
      if: always()
      with:
        name: docker-scout-artifact
        path: docker-scout-report.sarif

    
    
    
