name: Django Continuous Integration & Testing

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  code_scan:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create a Folder + File to host Bandit Artifacts
      run: | 
        mkdir -p artifacts
        touch artifacts/bandit-scan-report.json
        
    - name: Bandit Scan
      run: bandit -ll -ii -r . -f json -o bandit-scan-report.json
      
    - name: Upload Bandit Artifact
      uses: actions/upload-artifact@v6.0.0
      if: always()
      with:
        name: bandit-scan-artifact
        path: bandit-scan-report.json

  image_scan:

    name: Build Image and Run Image Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker-practice/actions-setup-docker@v1
      with:
        docker_version: '20.10'

    - name: Create a Folder + File to host Docker Scout Artifacts
      run: touch artifacts/docker-scout-report.sarif

    - name: Build Docker Image
      run: docker build -f Dockerfile -t djangoapp:latest .

    - name: Scan using Docker Scout
      uses: docker/scout-action@v1.18.2
      with:
        dockerhub-user: ${{ secrets.DOCKER_USER }}
        dockerhub-password: ${{ secrets.DOCKER_PWD }}
        command: quickview,cves
        only-severities: critical, high
        sarif-file: docker-scout-report.sarif
        exit-code: true

    - name: Upload Docker Scout Artifact
      uses: actions/upload-artifact@v6.0.0
      if: always()
      with:
        name: docker-scout-artifact
        path: artifacts/docker-scout-report.sarif

    
    
    
